### ISSUE TITLE
IE 11 does not work

### ISSUE THREAD

**Issue by markoj21** [Nolanus/ngx-multi-window#29] opened 2018-10-03 06:28 UTC
I was testing the project and it currently does not work with IE11, the send messages timeout.

**Comment by kayvanbree** [comment] 2018-10-03 12:19
Just abandon Internet Explorer and tell your users to use a decent browser. IE11 was released in October 2013 and there won't be a new version. Why would you want stuff to work on an old outdated browser?

**Comment by roscoedeemarutam** [comment] 2018-10-16 09:13
Also Edge gives me a timeout when sending messages? Anybody have an idea how to fix this?

**Comment by kayvanbree** [comment] 2018-10-16 10:19
I'm not at work or at home right now, I'll check this out later.

**Comment by Nolanus** [comment] 2018-10-30 12:54
Hi,

just investigated the problem in some fresh IE11's in Windows 7. I can reproduce the communication not happening as the localStorage doesn't get synced. The problem I came across is, that the localStorage keys do not get synced as expected. When opening the new window, it looks like it's taking a snapshot of the current localStorage keys and just keeps that.

This basic example hopefully illustrates that:
![screen shot 2018-10-30 at 13 41 27](https://user-images.githubusercontent.com/3458616/47718937-fe2ebf80-dc49-11e8-8730-b9acb9e76709.png)
![screen shot 2018-10-30 at 13 44 13](https://user-images.githubusercontent.com/3458616/47718935-fa02a200-dc49-11e8-8b04-82146bd06871.png)

Setting an item in Window A (left side) does not result it's key to be present in the "localStorage" object in Window B (right side). However, directly querying that key still returns the content. After reloading Window B the key is present on the Window B's localStorage object.

So either we one has to come up with a complicated mechanism that a new window "bumps" existing windows and reports its id, however, this changes the whole "new window detection mechanism".

Just stumbled upon the [`Storage.key()`](https://developer.mozilla.org/en-US/docs/Web/API/Storage/key) method though, which combined with `Storage.length` could be an alternative to `Object.keys(localStorage)`.

**Closed** 2018-10-30 13:18 UTC

**Comment by kayvanbree** [comment] 2018-11-01 09:06
I've read something about other techniques to do cross-window communication. [Something like this](https://javascript.info/cross-window-communication#cross-window-messaging). Using a method like that would eliminate the need for polling, theoretically making the communication quicker. I have never used it though. Also, I don't know about browser support and I think 3/4 of the library would have to be rewritten. 

[This person](https://stackoverflow.com/questions/28230845/communication-between-tabs-or-windows) had the same problem and they recommend using a [BroadcastChannel](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API). It's a simple API: 

```javascript
// Setup
var bc = new BroadcastChannel('test_channel');

// Broadcasting
bc.postMessage('This is a test message.');

// Receiving
bc.onmessage = function (ev) { console.log(ev); }

// Closing connection 
bc.close()
```

Problem is, [Edge doesn't support it yet](https://caniuse.com/#search=broadcastchannel), so it's of no use for this issue. I did find [a polyfill that could maybe work](https://medium.com/@alex89x/communication-among-iframes-and-tabs-a-working-polyfill-for-broadcast-channel-api-f44d07dcf527). It uses local storage though, so I don't know if that will work.

**Comment by kayvanbree** [comment] 2018-11-01 09:14
@Nolanus Why did you close this issue? Edge is still a problem?

**Comment by Nolanus** [comment] 2018-11-01 15:35
@kayvanbree yes, please see https://github.com/Nolanus/ngx-multi-window/commit/be5fdc04df6e686c5bc33438957a611ddf32ab50. This caused IE11 and Edge to not work for me, after implementing this change it works in both browsers. Please let me know if there are still problems with these browser.

Regarding the alternative solutions, can you please create a new issue for that (just copy/paste your comment), so wen can discuss this over there? Thanks!
